preload = ~/dotfiles/.github/wallpaper/evangelion_unit-01.png

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = eDP-1,~/dotfiles/.github/wallpaper/evangelion_unit-01.png

#enable splash text rendering over the wallpaper
splash = true
